import {AppBar, Button, IconButton, Dialog, DialogContent, TextField, Tabs, Tab} from "@mui/material";
import {useRef, useState} from "react";
import {Activity, AlertCircle, Box, ChevronDown, Code2, Command, Cpu, Database, FileOutput, FolderKanban, GitBranch, Home, ListChecks, MessagesSquare, PanelRight, PencilRuler, Search, Settings, TerminalSquare, X} from "lucide-react";
import type {ActivityId, ExecutionTarget, Project, Run} from "./types";
import brand from "./assets/favicon.svg";
import company from "./assets/modalitysystems.png";
export const activityIcons = {overview:Home,source:Code2,dataset:Database,annotation:PencilRuler,architecture:Box,training:Activity,inference:Search,runs:ListChecks,assistant:MessagesSquare,settings:Settings};
export const railLabels:Record<ActivityId,string> = {overview:"Overview",source:"Source",dataset:"Datasets",annotation:"Annotate",architecture:"Models",training:"Training",inference:"Inference",runs:"Jobs",assistant:"Assistant",settings:"Settings"};
export function Brand(){return <span className="product-identity"><img className="brand-symbol" src={brand} alt=""/><span className="brand-word"><span>Model</span><strong>Forge</strong></span></span>;}
export function TitleBar({projects,project,target,onTarget,onProject,run,onHome,onCommands,onInspector,connection}:{projects:Project[];project:Project|null;target:ExecutionTarget|null;onTarget:(value:ExecutionTarget|null)=>void;onProject:(id:string)=>void;run:Run|null;onHome:()=>void;onCommands:()=>void;onInspector:()=>void;connection:string}){
 const active=run&&["running","queued"].includes(run.status), percent=active?run?.live?.progress?.percent:0;
 return <AppBar component="header" position="static" color="transparent" elevation={0} className="title-bar"><Button className="product-brand" aria-label="ModelForge Home" onClick={onHome}><Brand/></Button><label className="project-switcher"><FolderKanban size={15}/><select aria-label="Project" value={project?.id||""} onChange={event=>onProject(event.target.value)}>{projects.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><div className="execution-toolbar"><span className={`execution-location ${target?.billable?"cloud":""}`}>{target?.target||"LOCAL"}</span><div className="execution-device"><Cpu size={15}/><select aria-label="Toolbar execution target" value={target?.target||""} onChange={event=>onTarget(project?.execution_targets?.find(item=>item.target===event.target.value)||null)}>{project?.execution_targets?.map(item=><option key={item.target} value={item.target}>{item.target} · {item.readiness||"unavailable"}</option>)}</select></div><div className={`execution-job ${active?"active":""}`}><div><Activity size={12}/><span><strong>{active?run?.live?.progress?.stage||run?.status:"Idle"}</strong></span></div></div><div className="execution-progress" role="progressbar" aria-label="Execution progress" aria-valuemin={0} aria-valuemax={100} aria-valuenow={percent}><i style={{width:`${Math.max(0,Math.min(100,percent??0))}%`}}/><span>{active?(percent===undefined?"Awaiting progress":`${percent}%`):""}</span></div></div><Button className="command-trigger" onClick={onCommands}><Search size={14}/><span>Search or run a command…</span><kbd>Ctrl K</kbd></Button><div className="title-actions"><IconButton className="icon-button" aria-label="Toggle inspector" onClick={onInspector}><PanelRight size={16}/></IconButton><span className="connection" role="status" aria-label={connection}><i className={connection.toLowerCase()}/><span>{connection}</span></span><span className="title-modality-logo"><img src={company} alt="Modality Systems"/></span></div></AppBar>;
}
export function BottomPanel({log,run,onJobs}:{log:string;run:Run|null;onJobs:()=>void}){
 const [open,setOpen]=useState(()=>localStorage.getItem("modelforge.output.open")==="true");const [tab,setTab]=useState("output");
 const firstSeen=useRef(new Map<string,string>()); const logRun=useRef(run?.id); if(logRun.current!==run?.id){firstSeen.current.clear();logRun.current=run?.id;}
 const lines=(run?.live?.log_tail||log).split(/\r?\n/).slice(-500);
 const visible=lines.map(line=>{if(!line||/^\[\d\d:\d\d:\d\d\]/.test(line))return line;let timestamp=firstSeen.current.get(line);if(!timestamp){timestamp=new Date().toLocaleTimeString("en-GB",{hour12:false});firstSeen.current.set(line,timestamp);}return `[${timestamp}] ${line}`;});
 const toggle=()=>setOpen(value=>{localStorage.setItem("modelforge.output.open",String(!value));return !value;});
 return <section className={`bottom-panel ${open?"open":"collapsed"}`} aria-label="Run log"><header><Tabs value={tab} aria-label="Output panels" onChange={(_event,value)=>{setTab(value);setOpen(true);localStorage.setItem("modelforge.output.open","true");if(value==="jobs")onJobs();}}>{[["output","Output",TerminalSquare],["logs","Logs",FileOutput],["problems","Problems",AlertCircle],["jobs","Jobs",ListChecks]].map(([id,label,Icon])=>{const Glyph=Icon as typeof TerminalSquare;return <Tab key={String(id)} value={id} onClick={()=>{setOpen(true);localStorage.setItem("modelforge.output.open","true");}} icon={<Glyph size={13}/>} iconPosition="start" label={String(label)}/>;})}</Tabs><IconButton className="icon-button" aria-label={open?"Collapse output panel":"Expand output panel"} onClick={toggle}><ChevronDown size={15} className={open?"":"rotate-180"}/></IconButton></header>{open&&<div className="bottom-panel-content" role="tabpanel"><pre>{tab==="problems"?(run?.error||"No current run errors."):tab==="jobs"?(run?`${run.id} · ${run.status}`:"No run selected."):visible.join("\n")||"Select a run to view recorded output."}</pre></div>}</section>;
}
export function AssistantPanel({activity,onClose,onRun}:{activity:string;onClose:()=>void;onRun:()=>void}){return <section className="assistant-panel"><header><img src={brand} alt=""/><div><strong>ModelForge Coding Assistant</strong><small>Local project assistant</small></div><Button aria-label="Run details" onClick={onRun}>Run</Button><IconButton className="icon-button" aria-label="Close assistant inspector" onClick={onClose}><X size={14}/></IconButton></header><div className="assistant-context">CONTEXT <span>{activity}</span></div><div className="assistant-introduction"><img src={brand} alt=""/><h3>Your ModelForge project agent</h3><p>The local assistant service is not connected in this build. Project editing and registered actions remain unavailable here.</p><Button disabled>Explain the selected {activity.toLowerCase()}</Button><Button disabled>Summarize the model and dataset lineage</Button><Button disabled>Compare the most recent recorded results</Button></div><div className="assistant-composer"><textarea disabled aria-label="Assistant prompt" placeholder="Assistant service unavailable"/><span>Project-scoped assistant connection required</span></div></section>;}
export function StatusBar({project,activity,target}:{project:Project|null;activity:string;target:ExecutionTarget|null}){return <footer className="status-bar"><div><span><GitBranch size={11}/>local</span><span><Database size={11}/>{project?.dataset?.name||"No dataset"}</span><span><Box size={11}/>{project?.name||"No project"}</span></div><div><span>{target?.target||"Local"}</span><span>{activity}</span><span className="product-release"><strong>ALPHA</strong>v0.1.0a1</span></div></footer>;}
export function CommandPalette({items,onSelect,onClose}:{items:{id:ActivityId;label:string}[];onSelect:(id:ActivityId)=>void;onClose:()=>void}){const [query,setQuery]=useState("");return <Dialog open onClose={onClose} aria-label="Command palette" fullWidth maxWidth="sm"><DialogContent className="command-dialog"><TextField autoFocus fullWidth placeholder="Search workspaces…" label="Search commands" value={query} onChange={event=>setQuery(event.target.value)}/><div className="command-results">{items.filter(item=>item.label.toLowerCase().includes(query.toLowerCase())).map(item=><Button key={item.id} onClick={()=>{onSelect(item.id);onClose();}}>{item.label}</Button>)}</div><Button onClick={onClose}>Close</Button></DialogContent></Dialog>;}
